# Generated by Django 4.2.30 on 2026-07-11 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="заголовок")),
                ("description", models.TextField(blank=True, verbose_name="текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создан")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="pets.pet",
                        verbose_name="питомец",
                    ),
                ),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
                "ordering": ("-created_at",),
            },
        ),
    ]
