# Generated by Django 4.2.30 on 2026-07-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='posts.post', verbose_name='пост')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='posts.tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'тег поста',
                'verbose_name_plural': 'теги постов',
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.FileField(upload_to='posts/media/', verbose_name='файл')),
                ('media_type', models.CharField(choices=[('image', 'изображение'), ('video', 'видео')], default='image', max_length=10, verbose_name='тип')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'медиафайл поста',
                'verbose_name_plural': 'медиафайлы поста',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='posts.PostTag', to='posts.tag', verbose_name='теги'),
        ),
    ]
