# Generated by Django 4.2.30 on 2026-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=30, verbose_name="Пол"),
        ),
        migrations.AddField(
            model_name="user",
            name="info",
            field=models.TextField(blank=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="user",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50, verbose_name="Местоимения"),
        ),
    ]
