services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: crazy_mops
      POSTGRES_USER: crazy_mops
      POSTGRES_PASSWORD: crazy_mops
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: