# Generated by Django 4.2.30 on 2026-07-13 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0002_commentmedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_tag_posttag_postmedia_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reaction_type",
                    models.SmallIntegerField(
                        choices=[(0, "лайк"), (1, "сердце"), (2, "смех"), (3, "вау")], verbose_name="тип реакции"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создана")),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="comments.comment",
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="posts.post",
                        verbose_name="пост",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "реакция",
                "verbose_name_plural": "реакции",
            },
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("comment__isnull", True), ("post__isnull", False)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="reaction_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)), fields=("post", "user"), name="reaction_unique_post_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("user", "comment"),
                name="reaction_unique_user_comment",
            ),
        ),
    ]
