# Generated by Django 4.2.30 on 2026-07-10 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Кличка")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="pets/avatars/", verbose_name="Аватар")),
                ("breed", models.CharField(blank=True, max_length=100, verbose_name="Порода")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Дата рождения")),
                ("eye_color", models.CharField(blank=True, max_length=50, verbose_name="Цвет глаз")),
                ("coat_color", models.CharField(blank=True, max_length=50, verbose_name="Окрас")),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("dog", "Собака"),
                            ("cat", "Кошка"),
                            ("bird", "Птица"),
                            ("rodent", "Грызун"),
                            ("reptile", "Рептилия"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "sex",
                    models.SmallIntegerField(
                        blank=True, choices=[(0, "Мальчик"), (1, "Девочка")], null=True, verbose_name="Пол"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Питомец",
                "verbose_name_plural": "Питомцы",
                "ordering": ["name"],
            },
        ),
    ]
