# Generated by Django 4.2.30 on 2026-07-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_url", models.FileField(upload_to="comment_media/")),
                (
                    "media_type",
                    models.CharField(choices=[("image", "Изображение"), ("video", "Видео")], max_length=10),
                ),
                ("display_order", models.SmallIntegerField(default=0)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media", to="comments.comment"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
